namespace BS2BG.Core.Diagnostics;

/// <summary>
/// Immutable container for grouped project health findings and severity totals.
/// </summary>
public sealed class ProjectValidationReport
{
    /// <summary>
    /// Creates a validation report from a materialized finding collection.
    /// </summary>
    /// <param name="findings">Findings generated by a read-only validation pass.</param>
    public ProjectValidationReport(IEnumerable<DiagnosticFinding> findings)
    {
        Findings = (findings ?? throw new ArgumentNullException(nameof(findings))).ToArray();
        BlockerCount = Findings.Count(finding => finding.Severity == DiagnosticSeverity.Blocker);
        CautionCount = Findings.Count(finding => finding.Severity == DiagnosticSeverity.Caution);
        InfoCount = Findings.Count(finding => finding.Severity == DiagnosticSeverity.Info);
    }

    public IReadOnlyList<DiagnosticFinding> Findings { get; }

    public int BlockerCount { get; }

    public int CautionCount { get; }

    public int InfoCount { get; }
}
